fix issue #7 NoClassDefFoundError: com/intellij/util/PathKt I can't explain the root cause, but using another static import based on JRE solves the issue semantics are fully preserved